
#can add border colors here but its in the main file
#Opacity means transparency. 0 equals fully see through, 1 equals standard non-see through windows. 

decoration { 
	rounding = 0
	rounding_power = 0
	
	active_opacity = 1.0
	inactive_opacity = 1.0

	shadow { 
		enabled = true
		range = 4
		render_power = 5
		#color = rgba(255, 255, 255, 1)
		color = rgba(125, 162, 171, 1)
		#color = rgba(1a1a1aee)
	}

	blur {
		enabled = true
		size = 3
		passes = 1

		vibrancy = 0.1696
	}
}
