
#Setting window rules // Fullscreen force // Picture-in-Picture // etc.

windowrule { 
	name = suppress-maximize-events
	match:class = .*
	
	suppress_event = maximize
}

windowrule {
	name = fix-xwayland-drags
	match:class = ^$
	match:title = ^$
	match:xwayland = true
	match:float = true
	match:fullscreen = false
	match:pin = false

	no_focus = true
}

windowrule {
	name = move-hyprland-run

	match:class = move-hyprland-run

	move = 20 monitor_h-120
	float = yes
}



#MY RULES --------------------------


	#music workspace

workspace = special:magic, on-created-empty:strawberry
windowrule = match:workspace special:magic, no_screen_share 1, persistent_size on, 

	#Can be for anything, but I have it set as discord/vesktop personally

workspace = special:discord, on-created-empty:vesktop, border:false
windowrule = match:workspace special:terminal, no_screen_share 1, persistent_size on	
